### ISSUE TITLE
Currate launch content

### ISSUE THREAD

**Issue by johnbarrierwilson** [northlandchurch/Distributed-Church#3]
Content doesn't need to be everything that needs to be on the site. Just a handful of these different types of content should do as we can add more, later, as the site ages.

Content that needs to be created and curated:
- [ ] Homepage tagline description
- [ ] Homepage blog description
- [ ] Homepage guides description
- [ ] Blog page description
- [ ] 3 - 4 blog posts w/ category names and short descriptions for each post
- [ ] Guide titles, content and short descriptions for each guide
- [ ] Join the movement steps

In regards to the "join the movement steps," I was thinking we should go with something like [Dave Ramsey's baby steps](https://www.daveramsey.com/new/baby-steps/). These encourage people to learn and grow in a new lifestyle of living, not simply a checklist of things to do and mark as complete.

**Comment by jhnwlsn** [comment]
Hey Chad! Not sure if you saw this issue on Github, but should be a good place to go ahead and dump all the content that you have been working on. Similarly to last time, we can pick up all project communication here in Github now that we are in mostly development stages. Let me know if you have any questions/concerns!

**Comment by jhnwlsn** [comment]
@chadturnbull < Just a mention to make sure it triggers an email. ;)
